alerting:
  alertmanager:
    url: "http://alertmanager:9093"
    timeout: 10s
    default-severity: "critical"
    extra-labels:
      environment: "test"
    default-alert:
      enabled: true
      failure-threshold: 2
      success-threshold: 1
      send-on-resolved: true

endpoints:
  # Controllable endpoints - you have full control via API/script
  - name: "API Service"
    url: "http://test-server:8080/health/api"
    interval: 15s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].healthy == true"
    alerts:
      - type: alertmanager
        description: "API service health check failed"
        failure-threshold: 1  # Fast failure for testing

  - name: "Database Service"
    url: "http://test-server:8080/health/database"
    interval: 15s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].healthy == true"
    alerts:
      - type: alertmanager
        description: "Database connectivity failed"
        failure-threshold: 1

  - name: "Cache Service"
    url: "http://test-server:8080/health/cache"
    interval: 15s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].healthy == true"
    alerts:
      - type: alertmanager
        description: "Cache service unavailable"
        failure-threshold: 1
        provider-override:
          extra-labels:
            severity: "warning"

  # Automatic time-based toggles (no manual control needed)
  - name: "Minute Toggle"
    url: "http://test-server:8080/time-based"
    interval: 15s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].healthy == true"
    alerts:
      - type: alertmanager
        description: "Time-based test (fails on even minutes)"
        failure-threshold: 1

  - name: "Second Toggle"
    url: "http://test-server:8080/second-based"
    interval: 10s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].healthy == true"
    alerts:
      - type: alertmanager
        description: "Fast toggle test (fails seconds 0-19)"
        failure-threshold: 1

  # Simple always-failing test
  - name: "Always Failing Test"
    url: "https://httpbin.org/status/500"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: alertmanager
        description: "Test endpoint that always fails"
        failure-threshold: 1
        provider-override:
          extra-labels:
            severity: "warning"
            test_type: "constant_failure"
